apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pgadmin.deploymentName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.pgadmin.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.pgadmin.templateLabel }}
    spec:
      containers:
        - name: {{ .Values.pgadmin.containerName }}
          image: {{ .Values.pgadmin.image }}
          ports:
            - containerPort: {{ .Values.pgadmin.containerPort }}
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: PGADMIN_DEFAULT_PASSWORD