apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: standard
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29tCg==  # base64 'admin@admin.com'
  PGADMIN_DEFAULT_PASSWORD: cm9vdAo=  # base64 'root'