apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgadmin.secret.email }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgadmin.secret.password}}