apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgadmin.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.pgadmin.appLabel }}
  ports:
    - port: {{ .Values.pgadmin.containerPort }}
      nodePort: {{ .Values.pgadmin.nodePort }}