apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.postgres.appLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.containerPort }}
      targetPort: {{ .Values.postgres.containerPort }}