apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  password: {{ .Values.postgres.secret.password | b64enc | quote }}
  user: {{ .Values.postgres.user | b64enc | quote }}
  db: {{ .Values.postgres.db | b64enc | quote }}