apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  password: {{ .Values.postgres.secret.password }}
  user: {{ .Values.postgres.user  }}
  db: {{ .Values.postgres.db }}