apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  password: {{ .Values.postgres.secret.password | b64enc }}
  user: {{ .Values.postgres.secret.user | b64enc }}
  database: {{ .Values.postgres.secret.database | b64enc }}