apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.statefulsetName }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.postgres.serviceName }}
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.templateLabel }}
    spec:
      containers:
        - name: {{ .Values.postgres.containerName }}
          image: {{ .Values.postgres.image }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: db
          ports:
            - containerPort: {{ .Values.postgres.containerPort }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.postgres.storageSize }}