apiVersion: v1
kind: Namespace
metadata:
  name: standard

---

apiVersion: v1
kind: Namespace
metadata:
  name: helm

---

apiVersion: v1
kind: Namespace
metadata:
  name: kustomize
