apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: standard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: alexb00/app_fastapi:latest
          resources:
            requests:
              cpu: "50m" # demande min CPU
            limits:
              cpu: "200m" # limite max CPU
          ports:
            - containerPort: 80