apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: standard
type: Opaque
data:
  password: cGFzc3dvcmQ=  # password
  user: YWRtaW4=  # admin
  database: c3RvcmVkYg==  # storedb