apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: standard
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

##apiVersion: v1
##kind: Service
##metadata:
##  name: postgres
##  namespace: standard
##  labels:
##    app: postgres
##spec:
##  ports:
##    - port: 5432
##      name: postgres
##  clusterIP: None
##  selector:
##    app: postgres