apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fastapi.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.fastapi.appLabel }}
  type: ClusterIP
  ports:
    - port: {{ .Values.fastapi.servicePort }}
      targetPort: {{ .Values.fastapi.containerPort }}
      protocol: TCP