host: "helm.alexisber.cloudns.be"
email: "bernealexis@gmail.com"
namespace: "helm"

fastapi:
  deploymentName: "fastapi-deployment"
  serviceName: "fastapi-service"
  image: "alexb00/app_fastapi:latest"
  cpuRequest: "50m"
  cpuLimit: "200m"
  replicas: 3
  servicePort: 5000
  appLabel: "fastapi"
  matchLabels: "fastapi"
  templateLabel: "fastapi"
  containerName: "fastapi"
  containerPort: 80
  hpa:
    name: "fastapi-hpa"
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70

service:
  type: ClusterIP
  port: 80

pgadmin:
  deploymentName: "pgadmin-deployment"
  serviceName: "pgadmin-service"
  image: "dpage/pgadmin4"
  containerPort: 80
  nodeport: 30081
  appLabel: "pgadmin"
  matchLabels: "pgadmin"
  templateLabel: "pgadmin"
  containerName: "pgadmin"
  secret:
    email: "admin@admin.com"
    password: "root"
    user: "YWRtaW4="

postgres:
  deploymentName: "postgres"
  serviceName: "db"
  replicas: 1
  storageSize: "10Gi"
  storagePath: "/mnt/data/helm"
  image: "postgres:latest"
  appLabel: "postgres"
  secretName: "postgres-secret"
  matchLabels:
    app: "postgres"
  templateLabel: "postgres"
  containerName: "postgres"
  containerPort: 5432
  pvcName: "postgres-pvc"
  secret:
    password: "cGFzc3dvcmQ="
    user: "YWRtaW4="
    db: "c3RvcmVkYg=="

ingress:
    enabled: true
    ingressName: "helm-ingress"
    ingressPath: "/"
    ingressServiceName: "helm"