host: "helm.alexisber.cloudns.be"
email: "bernealexis@gmail.com"
namespace: "helm"

secrets:
  postgres:
    password:
    User:
    database:
  pgadmin:
    password:
    email:

fastapi:
  deploymentName: "fastapi-deployment"
  serviceName: "fastapi-service"
  image: ""
  cpuRequest: "50m"
  cpuLimit: "200m"
  replicas: 3
  servicePort: 5000
  appLabel: "fastapi"
  matchLabels: "fastapi"
  templateLabel: "fastapi"
  containerName: "fastapi"
  containerPort: 80

hpa:
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

pgadmin:
  deploymentName: "pgadmin-deployment"
  serviceName: "pgadmin-service"
  image: "dpage/pgadmin4"
  containerPort: 80
  nodeport: 30081
  appLabel: "pgadmin"
  matchLabels: "pgadmin"
  templateLabel: "pgadmin"
  containerName: "pgadmin"

postgres:
  statefulsetName: "postgres-statefulset"
  serviceName: "db"
  replicas: 1
  storageSize: "10Gi"
  storagePath: "/mnt/data/helm"
  image: "postgres:latest"
  appLabel: "postgres"
  matchLabels: "postgres"
  templateLabel: "postgres"
  containerName: "postgres"
  containerPort: 5432