host: "helm.alexisber.cloudns.be"
email: "bernealexis@gmail.com"
namespace: "helm"

fastapi:
  deploymentName: "fastapi-deployment"
  serviceName: "fastapi-service"
  image: "alexb00/app_fastapi:latest"
  cpuRequest: "50m"
  cpuLimit: "200m"
  replicas: 3
  servicePort: 5000
  appLabel: "fastapi"
  matchLabels: "fastapi"
  templateLabel: "fastapi"
  containerName: "fastapi"
  containerPort: 80

hpa:
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

pgadmin:
  deploymentName: "pgadmin-deployment"
  serviceName: "pgadmin-service"
  image: "dpage/pgadmin4"
  containerPort: 80
  nodeport: 30081
  appLabel: "pgadmin"
  matchLabels: "pgadmin"
  templateLabel: "pgadmin"
  containerName: "pgadmin"

postgres:
  deploymentName: "postgres"
  serviceName: "db"
  replicas: 1
  storageSize: "10Gi"
  storagePath: "/mnt/data/helm"
  image: "postgres:latest"
  appLabel: "postgres"
  user: "yourPostgresUser"
  db: "yourPostgresDB"
  secretName: "postgres-secret"
  matchLabels:
    app: "postgres"
  templateLabel: "postgres"
  containerName: "postgres"
  containerPort: 5432
  pvcName: "postgres-pvc"